name: survey-mapper
channels:
  - conda-forge
  - esri
  - defaults
dependencies:
  - annotated-types=0.6.0
  - anyio=4.6.2
  - anywidget=0.9.13
  - appdirs=1.4.4
  - arcgis=2.4.1.1
  - arcgis-mapping=4.31.0
  - arcgispro=3.5
  - arcpy=3.5
  - arcpy-base=3.5
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=16.1.0
  - astor=0.8.1
  - asttokens=2.0.5
  - async-lru=2.0.4
  - asyncpg=0.27.0
  - attrs=24.3.0
  - autograd=1.5
  - autograd-gamma=0.5.0
  - aws-crt-cpp=0.27.4
  - aws-sdk-cpp-base=1.11.386
  - azure-core=1.12.0
  - azure-storage-blob=12.8.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - black=23.10.1
  - black-jupyter=23.10.1
  - blas=1.0
  - bleach=6.2.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - c-ares=1.19.1
  - cachetools=5.5.1
  - certifi=2025.8.3
  - cffi=1.17.1
  - cftime=1.6.4
  - chardet=4.0.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cppzmq=4.9.0
  - cryptography=43.0.1
  - cycler=0.11.0
  - cytoolz=1.0.1
  - dask=2024.12.1
  - dask-core=2024.12.1
  - dask-expr=1.1.21
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2024.12.1
  - dnspython=2.7.0
  - dpcpp-cpp-rt=2024.2.1
  - email-validator=2.3.0
  - email_validator=2.3.0
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.0.0rc9
  - executing=0.8.3
  - fastapi=0.117.1
  - fastapi-cli=0.0.13
  - fastapi-core=0.117.1
  - flake8=7.1.1
  - fonttools=4.55.3
  - formulaic=0.6.2
  - freetype=2.13.3
  - fsspec=2024.12.0
  - future=0.18.3
  - gdal=3.10.2
  - geomet=1.0.0
  - greenlet=3.1.1
  - h11=0.14.0
  - h5py=3.10.0
  - httpcore=1.0.2
  - httptools=0.6.4
  - httpx=0.27.0
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.0
  - iniconfig=1.1.1
  - intel-cmplr-lib-rt=2024.2.1
  - intel-cmplr-lib-ur=2024.2.1
  - intel-cmplr-lic-rt=2024.2.1
  - intel-core=2024.2.0
  - intel-fortran-rt=2024.2.1
  - intel-openmp=2024.2.1
  - intel-sycl-rt=2024.2.1
  - interface_meta=1.3.0
  - ipykernel=6.29.5
  - ipython=8.32.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - isodate=0.6.0
  - jdcal=1.4.1
  - jedi=0.18.2
  - jinja2=3.1.5
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.1
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - keyring=24.3.0
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - libabseil=20230125.3
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libdeflate=1.20
  - libpdal-base=2.8.4
  - libpng=1.6.43
  - libpq=12.17
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libthrift=0.20.0
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libxml2=2.12.10
  - libxslt=1.1.42
  - lifelines=0.30.0
  - locket=1.0.0
  - lxml=5.3.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mistune=3.1.2
  - mkl=2024.2.2
  - mkl-service=2.4.2
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - msrest=0.6.21
  - mypy_extensions=1.0.0
  - nbclassic=1.1.0
  - nbclient=0.8.0
  - nbconvert=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - netcdf4=1.6.4
  - networkx=3.4.2
  - nlohmann_json=3.11.2
  - nose=1.3.7
  - notebook=7.2.2
  - notebook-shim=0.2.4
  - numexpr=2.10.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - olefile=0.46
  - openpyxl=3.1.5
  - openssl=3.0.16
  - orc=2.0.0
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - pathspec=0.9.0
  - patsy=1.0.1
  - pefile=2022.5.30
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=23.3.2
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - pro_notebook_integration=3.5
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - protobuf=4.21.12
  - psutil=5.9.0
  - psycopg2=2.9.9
  - psycopg2-binary=2.9.9
  - psygnal=0.11.0
  - pure_eval=0.2.2
  - puremagic=1.15
  - pyarrow=16.1.0
  - pybind11=2.13.6
  - pybind11_json=0.2.13
  - pycodestyle=2.12.1
  - pycparser=2.21
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pydantic-settings=2.11.0
  - pyflakes=3.2.0
  - pygments=2.18.0
  - pyjwt=2.4.0
  - pylerc=4.0
  - pyodbc=5.2.0
  - pyparsing=3.2.0
  - pypdf=4.3.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pyspnego=0.11.1
  - pytest=7.4.3
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.1
  - python-duckdb=1.2.1
  - python-fastjsonschema=2.20.0
  - python-gssapi=1.8.3
  - python-json-logger=3.2.1
  - python-multipart=0.0.20
  - python-pdal=3.4.5
  - python_abi=3.11
  - pytz=2025.1
  - pywin32-ctypes=0.2.0
  - pywin32-security=306
  - pywinpty=2.0.14
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - re2=2023.06.02
  - referencing=0.30.2
  - regex=2024.11.6
  - requests=2.32.3
  - requests-gssapi=1.2.3
  - requests-kerberos=0.14.0
  - requests-oauthlib=2.0.0
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rich-toolkit=0.15.1
  - rpds-py=0.22.3
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - saspy=4.3.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=75.8.0
  - shellingham=1.5.4
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlalchemy=2.0.32
  - sqlite=3.49.1
  - sspilib=0.1.0
  - stack_data=0.5.1
  - starlette=0.48.0
  - statsmodels=0.14.4
  - swat=1.13.3
  - sympy=1.12
  - tbb=2021.8.0
  - tbb4py=2021.8.0
  - tblib=1.7.0
  - terminado=0.17.1
  - testpath=0.5.0
  - tinycss2=1.1.1
  - tokenize-rt=6.0.0
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - truststore=0.10.0
  - typer=0.19.2
  - typer-slim=0.19.2
  - typer-slim-standard=0.19.2
  - typing-extensions=4.12.2
  - typing-inspection=0.4.1
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ucrt=10.0.26100.0
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - uvicorn=0.37.0
  - uvicorn-standard=0.37.0
  - vc=14.38
  - vs2015_runtime=14.38.33130
  - watchfiles=0.24.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=11.0.2
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - winkerberos=0.9.1
  - winpty=0.4.3
  - wrapt=1.17.0
  - xarray=2024.11.0
  - xeus=3.0.5
  - xeus-python=0.15.8
  - xeus-python-shell=0.6.3
  - xeus-python-shell-raw=0.6.3
  - xeus-zmq=1.0.2
  - xlrd=2.0.1
  - xlwt=1.3.0
  - xtl=0.7.5
  - xz=5.4.7
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zlib-ng=2.1.6
  - zstd=1.5.7
  - pip:
      - arcgis (archived)==2.4.1
