name: survey-mapper
channels:
  - conda-forge
  - esri
  - defaults
dependencies:
  - annotated-doc=0.0.4
  - annotated-types=0.6.0
  - anyio=4.7.0
  - anywidget=0.9.18
  - appdirs=1.4.4
  - arcgis=2.4.2
  - arcgis-mapping=4.33.0
  - arcgispro=3.6
  - arcpy=3.6
  - arcpy-base=3.6
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - astor=0.8.1
  - asttokens=3.0.0
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - asyncpg=0.31.0
  - attrs=24.3.0
  - autograd=1.7.0
  - autograd-gamma=0.5.0
  - aws-crt-cpp=0.27.4
  - aws-sdk-cpp-base=1.11.386
  - azure-core=1.12.0
  - azure-storage-blob=12.8.0
  - babel=2.16.0
  - beautifulsoup4=4.13.5
  - black=25.1.0
  - black-jupyter=25.1.0
  - blas=1.0
  - bleach=6.2.0
  - blinker=1.9.0
  - blosc=1.21.5
  - bottleneck=1.4.2
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cachetools=5.5.1
  - certifi=2025.11.12
  - cffi=1.17.1
  - cftime=1.6.4
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.2.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cppzmq=4.9.0
  - crc32c=2.7.1
  - cryptography=43.0.1
  - csaps=1.3.2
  - cycler=0.11.0
  - cytoolz=1.0.1
  - dask=2025.2.0
  - dask-core=2025.2.0
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distributed=2025.2.0
  - dnspython=2.7.0
  - donfig=0.8.1.post1
  - dpcpp-cpp-rt=2024.2.1
  - email-validator=2.3.0
  - email_validator=2.3.0
  - entrypoints=0.4
  - et_xmlfile=2.0.0
  - exceptiongroup=1.0.0rc9
  - executing=2.2.1
  - fastapi=0.124.0
  - fastapi-cli=0.0.16
  - fastapi-core=0.124.0
  - fissix=24.4.24
  - flake8=7.1.1
  - fonttools=4.55.3
  - formulaic=0.6.2
  - freetype=2.13.3
  - fsspec=2025.7.0
  - future=1.0.0
  - gdal=3.11.3
  - geomet=1.0.0
  - greenlet=3.2.4
  - h11=0.16.0
  - h5py=3.14.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.0
  - iniconfig=1.1.1
  - intel-cmplr-lib-rt=2024.2.1
  - intel-cmplr-lib-ur=2024.2.1
  - intel-cmplr-lic-rt=2024.2.1
  - intel-core=2024.2.0
  - intel-fortran-rt=2024.2.1
  - intel-openmp=2024.2.1
  - intel-sycl-rt=2024.2.1
  - interface_meta=1.3.0
  - ipykernel=6.29.5
  - ipython=8.37.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - isodate=0.6.0
  - jdcal=1.4.1
  - jedi=0.18.2
  - jinja2=3.1.6
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.8
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kerchunk=0.2.8
  - keyring=24.3.0
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - libabseil=20250127.0
  - libarrow=20.0.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libdeflate=1.20
  - libkrb5=1.21.3
  - libpdal-base=2.9.0
  - libpng=1.6.43
  - libpq=17.6
  - libprotobuf=5.29.5
  - libsodium=1.0.20
  - libthrift=0.21.0
  - libtiff=4.7.1
  - libutf8proc=2.10.0
  - libxml2=2.14.5
  - libxslt=1.1.43
  - lifelines=0.30.0
  - locket=1.0.0
  - lxml=6.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mistune=3.1.2
  - mkl=2024.2.2
  - mkl-service=2.4.2
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpmath=1.3.0
  - msgpack-python=1.1.1
  - msrest=0.6.21
  - mypy_extensions=1.0.0
  - nbclassic=1.1.0
  - nbclient=0.8.0
  - nbconvert=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - notebook=7.3.3
  - notebook-shim=0.2.4
  - numcodecs=0.14.1
  - numexpr=2.10.2
  - numpy=2.2.0
  - numpy-base=2.2.0
  - oauthlib=3.2.2
  - olefile=0.46
  - openpyxl=3.1.5
  - openssl=3.0.18
  - orc=2.1.2
  - overrides=7.4.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.1
  - parso=0.8.4
  - partd=1.4.2
  - pathspec=0.9.0
  - patsy=1.0.1
  - pefile=2022.5.30
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - pro_notebook_integration=3.6
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - protobuf=5.29.5
  - psutil=7.0.0
  - psycopg2=2.9.10
  - psycopg2-binary=2.9.10
  - psygnal=0.11.0
  - pure_eval=0.2.3
  - puremagic=1.15
  - pyarrow=20.0.0
  - pybind11=2.13.6
  - pybind11_json=0.2.13
  - pycodestyle=2.12.1
  - pycparser=2.23
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydantic-settings=2.12.0
  - pyflakes=3.2.0
  - pygments=2.18.0
  - pyjwt=2.4.0
  - pylerc=4.0
  - pyodbc=5.2.0
  - pyparsing=3.2.0
  - pypdf=4.3.1
  - pysocks=1.7.1
  - pyspnego=0.11.2
  - pytest=8.4.2
  - python=3.13.7
  - python-dateutil=2.9.0post0
  - python-dotenv=1.2.1
  - python-duckdb=1.3.2
  - python-fastjsonschema=2.20.0
  - python-gssapi=1.9.0
  - python-json-logger=3.2.1
  - python-multipart=0.0.20
  - python-pdal=3.4.5
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.1
  - pywin32-ctypes=0.2.2
  - pywin32-security=310
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - re2=2025.06.26
  - referencing=0.30.2
  - regex=2024.11.6
  - requests=2.32.5
  - requests-gssapi=1.3.0
  - requests-kerberos=0.14.0
  - requests-oauthlib=2.0.0
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=14.2.0
  - rich-toolkit=0.17.0
  - rpds-py=0.22.3
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.12
  - saspy=4.3.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=79.0.1
  - shellingham=1.5.4
  - six=1.16.0
  - snappy=1.2.2
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlalchemy=2.0.44
  - sqlite=3.50.4
  - sspilib=0.3.1
  - stack_data=0.5.1
  - starlette=0.50.0
  - statsmodels=0.14.5
  - sympy=1.14.0
  - tbb=2022.0.0
  - tbb4py=2022.0.0
  - tblib=3.1.0
  - terminado=0.18.1
  - testpath=0.5.0
  - tinycss2=1.1.1
  - tk=8.6.15
  - tokenize-rt=6.0.0
  - tomli=2.3.0
  - toolz=1.0.0
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - truststore=0.10.0
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.26100.1742
  - ujson=5.10.0
  - urllib3=2.5.0
  - uvicorn=0.38.0
  - uvicorn-standard=0.38.0
  - vc=14.38
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - watchfiles=0.24.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=15.0.1
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.17.0
  - xarray=2025.4.0
  - xeus=3.2.0
  - xeus-python=0.15.13
  - xeus-python-shell=0.6.3
  - xeus-python-shell-raw=0.6.3
  - xeus-zmq=1.3.0
  - xlrd=2.0.1
  - xlwt=1.3.0
  - xtl=0.7.5
  - xz=5.4.7
  - yaml=0.2.5
  - zarr=3.0.8
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zlib-ng=2.2.4
  - zstd=1.5.7
